### ISSUE TITLE
Missing "passport" package from package.json - 3.0.21

### ISSUE THREAD

**Issue by NorthernMan54** [oznu/homebridge-syno-spk#141]
### Raspberry Pi Model

Other (specify in description)

### Describe The Bug

7m[12/31/2023, 4:31:57 PM][0m [36m[HB Supervisor][0m OS: Linux 4.4.302+ x64
[37m[12/31/2023, 4:31:57 PM][0m [36m[HB Supervisor][0m Node.js v18.15.0 /volume1/@appstore/Node.js_v18/usr/local/bin/node
[37m[12/31/2023, 4:31:57 PM][0m [36m[HB Supervisor][0m Homebridge Path: /volume1/homebridge/node_modules/homebridge/bin/homebridge
[37m[12/31/2023, 4:31:57 PM][0m [36m[HB Supervisor][0m UI Path: /var/packages/homebridge/target/app/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[37m[12/31/2023, 4:31:58 PM][0m [36m[HB Supervisor][0m ERROR: The user interface threw an unhandled error
Error: Cannot find module 'passport'
Require stack:
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/passport/dist/auth.guard.js
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/passport/dist/index.js
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/passport/index.js
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/passport/dist/auth.guard.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {

### Logs

```text
7m[12/31/2023, 4:31:57 PM][0m [36m[HB Supervisor][0m OS: Linux 4.4.302+ x64
[37m[12/31/2023, 4:31:57 PM][0m [36m[HB Supervisor][0m Node.js v18.15.0 /volume1/@appstore/Node.js_v18/usr/local/bin/node
[37m[12/31/2023, 4:31:57 PM][0m [36m[HB Supervisor][0m Homebridge Path: /volume1/homebridge/node_modules/homebridge/bin/homebridge
[37m[12/31/2023, 4:31:57 PM][0m [36m[HB Supervisor][0m UI Path: /var/packages/homebridge/target/app/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[37m[12/31/2023, 4:31:58 PM][0m [36m[HB Supervisor][0m ERROR: The user interface threw an unhandled error
Error: Cannot find module 'passport'
Require stack:
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/passport/dist/auth.guard.js
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/passport/dist/index.js
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/passport/index.js
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/passport/dist/auth.guard.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
```

**Comment by NorthernMan54** [comment]
Added passport back to config-ui-x - https://github.com/homebridge/homebridge-config-ui-x/pull/1964

**Comment by NorthernMan54** [comment]
Also being discussed here - https://discord.com/channels/432663330281226270/973824041238528060

**Comment by NorthernMan54** [comment]
The release 3.0.21 has been unpublished - http://repo.homebridge.io/synology-spk-repo.json

**Comment by DaGreenX** [comment]
> The release 3.0.21 has been unpublished - http://repo.homebridge.io/synology-spk-repo.json

Hi @NorthernMan54, what should do with this link on my synology ?

**Comment by NorthernMan54** [comment]
That link is just the manifest file that is being read by the synology package centre - no need to do anything.  I was using that to reference and ensure I was successful in rolling back the release.

**Comment by DaGreenX** [comment]
Ok thanks :)
I still see version 3.0.21 in DSM at the moment.

**Comment by dficken** [comment]
NorthernMan,

Seeing 3.0.20 as latest version in the Synology package center.  Any advice on how to rollback?  Trying to avoid a complete uninstall / reinstall

Thanks!

**Comment by NorthernMan54** [comment]
3.0.20 is the rollback, 3.0.21 is the 'broken package'

**Comment by dficken** [comment]
How do I perform the rollback?  Uninstall / Reinstall or other?

**Comment by DaGreenX** [comment]
Yes. works for me : 
follow this : https://github.com/homebridge/homebridge-syno-spk/releases
No data lost, configuration is still there.

**Comment by NorthernMan54** [comment]
Release `3.1.0` has been published with NodeJS 20 support and the fix for this issue

**Comment by DaGreenX** [comment]
👍
