### ISSUE TITLE
Homebridge Not Running

### ISSUE THREAD

**Issue by JLF69** [oznu/homebridge-syno-spk#36]
Hi, I have installed Homebridge again on a new Synology Diskstation.  It has seemingly picked up my previous config.json file and other settings, but doesn't seem to be working correctly as the Homebridge UI reports 'Homebridge Not Running'.  It's been a few years since I originally installed Homebridge so I've probably forgotten something, but I followed my notes from last time round and still can't see what Im doing wrong.

Any help much appreciated.

**Comment by JSVarga** [comment]
I have been running to a while then upgraded to latest version. It failed. Try to manually install package, failed. Try to delete and reinstall 1.0.7 and it won't run but still has same version number. I do wonder about the Node.js version, only v12.14 available. Here are the error messages from the log.

[4/28/2020, 12:44:09 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c0fc8d68-7c06-40ce-b5ea-554fc650a021
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:287:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:268:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by JLF69** [comment]
I finally resolved my issue!  I realised that the Nest Plugin was having an issue.  I removed the Nest Plugin and voila!, Homebridge now works again.  So I can only assume that whatever the Nest plugin was trying to do and failing at was stopping Homebridge as a whole from running.
