### ISSUE TITLE
TCP Timeout issue 

### ISSUE THREAD

**Issue by slvrscoobie** [oznu/homebridge-syno-spk#59]
I installed, 2.0 from 1.0, but every time I do, it still re-installs the old plugins. Ive tried to delete the folder, but it still persists, when uninstalling and reinstalling the package. when I installed it, I restored the old home bridge. works good, but I have one issue: 
Issue is after a few minutes I start to get these TCP timeout - Im not really sure what this means. This the TPLink plugin. It was working fine with home bridge on 6.2 but now it has this error. Ive reached out to that dev too but havent heard back. 
Im not sure where I can delete the files so when I uninstall and reinstall the package I can do a fresh install. Im wondering if there is a folder / file issue? 

[1/2/2022, 12:53:32 PM] [TplinkSmarthome.API] TCP 192.168.44.41:9999 Error: TCP Timeout after 15000ms
192.168.44.41:9999 {"smartlife.iot.smartbulb.lightingservice":{"get_light_state":{}}}
    at Timeout._onTimeout (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[1/2/2022, 12:53:32 PM] [TplinkSmarthome.API] [Coop Light] device.send() Error: TCP Timeout after 15000ms
192.168.44.41:9999 {"smartlife.iot.smartbulb.lightingservice":{"get_light_state":{}}}
    at Timeout._onTimeout (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by slvrscoobie** [comment]
Looks like deleting everything and starting again from scratch fixed the issue, not sure what it was but maybe a plugin config that didnt like whatever changed from 1 -> 2.
